### ISSUE TITLE
When to stop device searching

### ISSUE THREAD

**Issue by sowd** [futomi/node-echonet-lite#2]
Hi,

I would like to search all connected ECHONET Lite devices.
When is the right timing to call el.stopDiscovery() ?

**Comment by futomi** [comment]
Thanks for your comment.

Though it is encouraged to call stopDiscovery() in the document, you don't need to call the stopDiscovery() actually If you use 'lan' mode for the network layer. In fact, the stopDiscovery() does nothing in the 'lan' mode.

But if you use `wisunb' mode, be sure to call the stopDiscovery() immediately after a smart meter is discovered. If you don't call the method, the subsequent requests probably won't work well.

Cheers.

**Comment by sowd** [comment]
Thank you for the suggestion. I will follow the advice.
