### ISSUE TITLE
Is it possible to modify self-EOJ?

### ISSUE THREAD

**Issue by sowd** [futomi/node-echonet-lite#3]
The document says :

> This node-echonet-lite module uses the EOJ [0x05, 0xFF, 0x01] as itself (i.e. you). This EOJ means the Controller class in the management, control-related device class group, and instance code 1.

Is there a way to change this?
Such changeability is useful to develop emulators, or interface of home appliances, and so on.

**Comment by futomi** [comment]
Thanks for your idea! It sounds good.

I added the `setSelfEoj()` method newly for you. I hope it's just what you want. See [the relevant section](https://github.com/futomi/node-echonet-lite#setSelfEoj-method) in the document for details.

Cheers.

**Comment by sowd** [comment]
What a quick res! Thank you so much!

**Comment by sowd** [comment]
forgot to close this
