### ISSUE TITLE
Way to directly specify binary edt?

### ISSUE THREAD

**Issue by sowd** [futomi/node-echonet-lite#4]
Hi,
I am using setPropertyValue().
Currently, the edt should be specified as a specially-designed, epc-dependent JSON object.
Though it is convenient, is there an alternative way to directly specify a number array, as in the specification of ECHONET Lite?

**Comment by futomi** [comment]
Thanks for your request. Your demand makes sense. I'll update the `setPropertyValue()` so that the EDT part can be specified as not only a JSON object but also an `Buffer` object. I'll get on with it.

**Comment by futomi** [comment]
Done.
See the description for the [`setPropertyValue()`](https://github.com/futomi/node-echonet-lite#setPropertyValue-method) method in the document.

**Comment by sowd** [comment]
Wow!! Thank you for the quick development!
It works nicely.

Cheers!
